namespace ParserTenders
{
    public enum TypeArguments
    {
        Prev44,
        Curr44,
        Last44,
        Last223,
        Daily223,
        Attach,
        LastSign223,
        DailySign223,
        GpB,
        LastExp223,
        DailyExp223,
        GntWeb,
        ObTorgWeb,
        SpecTorgWeb,
        Web,
        Mrsk,
        Rosneft,
        Sakhalin,
        TektorgGazprom,
        TektorgInterRao,
        TektorgRzd,
        Prev615,
        Curr615,
        Last615,
        Web44
    }
}